services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - rasp-next-network
  rasp-next:
    image: skta3569/rasp-next:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - rasp-next-network
networks:
  rasp-next-network:
    driver: bridge
